"""Dataset profiling for Phase 1.

Produces the numbers you need to justify the subset choice and to anticipate
where forecasting will be hard. Writes a markdown report to reports/.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


def series_stats(long: pd.DataFrame) -> pd.DataFrame:
    """Per-series demand characteristics, including intermittency measures.

    ADI  = average interval between non-zero demand days.
    CV2  = squared coefficient of variation of NON-ZERO demand sizes.
    These two are the standard Syntetos-Boylan axes for classifying demand
    into smooth / erratic / intermittent / lumpy.
    """
    g = long.groupby(["store_id", "item_id"], observed=True)["sales"]

    n_periods = g.size()
    n_nonzero = g.apply(lambda s: int((s > 0).sum()))
    total = g.sum()
    mean = g.mean()

    adi = n_periods / n_nonzero.replace(0, np.nan)

    def _cv2(s: pd.Series) -> float:
        nz = s[s > 0]
        if len(nz) < 2 or nz.mean() == 0:
            return np.nan
        return float((nz.std() / nz.mean()) ** 2)

    cv2 = g.apply(_cv2)

    return pd.DataFrame(
        {
            "n_days": n_periods,
            "n_nonzero_days": n_nonzero,
            "zero_share": 1 - n_nonzero / n_periods,
            "total_units": total,
            "mean_daily": mean,
            "adi": adi,
            "cv2": cv2,
        }
    ).reset_index()


def classify_demand(stats: pd.DataFrame, adi_thr: float, cv2_thr: float) -> pd.DataFrame:
    """Syntetos-Boylan-Croston quadrants."""
    out = stats.copy()
    hi_adi = out["adi"] >= adi_thr
    hi_cv2 = out["cv2"] >= cv2_thr
    out["segment"] = np.select(
        [~hi_adi & ~hi_cv2, ~hi_adi & hi_cv2, hi_adi & ~hi_cv2, hi_adi & hi_cv2],
        ["smooth", "erratic", "intermittent", "lumpy"],
        default="unknown",
    )
    return out


def profile(long: pd.DataFrame, adi_thr: float = 1.32, cv2_thr: float = 0.49) -> dict:
    stats = classify_demand(series_stats(long), adi_thr, cv2_thr)

    return {
        "n_rows": len(long),
        "n_series": long.groupby(["store_id", "item_id"], observed=True).ngroups,
        "n_items": long["item_id"].nunique(),
        "n_stores": long["store_id"].nunique(),
        "date_min": long["date"].min(),
        "date_max": long["date"].max(),
        "n_days": long["date"].nunique(),
        "overall_zero_share": float((long["sales"] == 0).mean()),
        "by_category": long.groupby("cat_id", observed=True)
        .agg(series=("item_id", "nunique"), units=("sales", "sum"),
             zero_share=("sales", lambda s: float((s == 0).mean())))
        .reset_index(),
        "by_store": long.groupby("store_id", observed=True)
        .agg(series=("item_id", "nunique"), units=("sales", "sum"))
        .reset_index(),
        "segments": stats["segment"].value_counts().reset_index(),
        "series_stats": stats,
        "price_missing_share": float(long["sell_price"].isna().mean())
        if "sell_price" in long.columns else None,
    }


def write_report(prof: dict, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    L = []
    L.append("# Phase 1 - M5 Data Profile\n")
    L.append("Generated by `src/profile.py`. All figures from observed M5 sales.\n")
    L.append("## Scope\n")
    L.append(f"- Rows: {prof['n_rows']:,}")
    L.append(f"- Series (item x store): {prof['n_series']:,}")
    L.append(f"- Items: {prof['n_items']:,} | Stores: {prof['n_stores']}")
    L.append(f"- Date range: {prof['date_min'].date()} to {prof['date_max'].date()} "
             f"({prof['n_days']:,} days)")
    L.append(f"- Overall zero-sales share: {prof['overall_zero_share']:.1%}")
    if prof["price_missing_share"] is not None:
        L.append(f"- Rows without a price: {prof['price_missing_share']:.2%}")

    L.append("\n## By category\n")
    L.append(prof["by_category"].to_markdown(index=False))
    L.append("\n## By store\n")
    L.append(prof["by_store"].to_markdown(index=False))

    L.append("\n## Demand segmentation (Syntetos-Boylan)\n")
    L.append(prof["segments"].to_markdown(index=False))
    L.append(
        "\n`intermittent` and `lumpy` series are where MAPE breaks down and where "
        "standard ML regressors tend to collapse toward zero. Phase 5 treats them "
        "separately rather than reporting one blended metric.\n"
    )
    path.write_text("\n".join(L))
    return path
